package reasons

const (
	TOKEN_EXPIRED         = "TOK_EXP"
	TOKEN_INVALID         = "TOK_INVALID"
	TOKEN_MISSING         = "TOK_MISSING"
	SESSION_IMPOSIBLE     = "SESS_IMPOSIBLE"
	SESSION_INV_CREDS     = "SESS_INV_CREDS"
	SESSION_MISSING_CREDS = "SESS_MISS_CREDS"
	SESSION_MISSING_USER  = "SESS_MISS_USER"
	INTERNAL_ERROR        = "INT_ERROR"
)
